// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMlQQt7y77TKzk0PuMYLiILgPTP_rJ0ac',
    appId: '1:169772912423:web:707a14c838c4be52666302',
    messagingSenderId: '169772912423',
    projectId: 'body-pilates-200a2',
    authDomain: 'body-pilates-200a2.firebaseapp.com',
    storageBucket: 'body-pilates-200a2.firebasestorage.app',
    measurementId: 'G-BF7VQM9LTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MEgHhIlRg01h-meboVi39CXiN_bdOAg',
    appId: '1:169772912423:android:7d3e431707c4f6e5666302',
    messagingSenderId: '169772912423',
    projectId: 'body-pilates-200a2',
    storageBucket: 'body-pilates-200a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3eIDALCf35LwwhWhCm5eVRjd2pHx4s4',
    appId: '1:169772912423:ios:ecb16a1a53f515ac666302',
    messagingSenderId: '169772912423',
    projectId: 'body-pilates-200a2',
    storageBucket: 'body-pilates-200a2.firebasestorage.app',
    iosBundleId: 'com.example.bodyPilates',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMlQQt7y77TKzk0PuMYLiILgPTP_rJ0ac',
    appId: '1:169772912423:web:e1832ef9f61a2d35666302',
    messagingSenderId: '169772912423',
    projectId: 'body-pilates-200a2',
    authDomain: 'body-pilates-200a2.firebaseapp.com',
    storageBucket: 'body-pilates-200a2.firebasestorage.app',
    measurementId: 'G-8R2Z6FBLQD',
  );
}
